[app]
name = "Sponsors"
category = "Badge"

[entry]
class = "Sponsors"

[metadata]
author = "sammachin"
license = "MIT"
url = "https://github.com/emfcamp/tildagon-sponsor-logos"
description = "Fullscreen sponsor logo slideshow"
version = "1.1.1"
